import { RangeOption, ScheduleData, TimeRange } from "@/components/schedule/types"

export const rangeOptions: RangeOption[] = [
  { key: "hoy", label: "Hoy" },
  { key: "manana", label: "Mañana" },
  { key: "semana", label: "Próximos 10 días" },
]

export const scheduleByRange: Record<TimeRange, ScheduleData> = {
  hoy: {
    arribos: [
      {
        buque: "Santa Regina",
        naviera: "Oceanic SA",
        hora: "08:15",
        estadia: "18 h",
        sitio: "Sitio 2",
        origen: "Montevideo",
        carga: "Contenedores",
        destino: "Terminal TecPlata",
        estado: "En tiempo",
      },
      {
        buque: "Patagonia Star",
        naviera: "Río Shipping",
        hora: "09:40",
        estadia: "22 h",
        sitio: "Sitio 1",
        origen: "Santos",
        carga: "Granel",
        destino: "Depósito Norte",
        estado: "Demorado 25 min",
      },
      {
        buque: "Blue Delta",
        naviera: "MarSur",
        hora: "11:10",
        estadia: "14 h",
        sitio: "Sitio 4",
        origen: "Bahía Blanca",
        carga: "Vehículos",
        destino: "Zona Operativa Sur",
        estado: "Confirmado",
      },
    ],
    salidas: [
      {
        buque: "Aurora Port",
        naviera: "Atlantic Cargo",
        hora: "10:00",
        estadia: "16 h",
        sitio: "Sitio 3",
        origen: "Puerto La Plata",
        carga: "Contenedores",
        destino: "Rotterdam",
        estado: "Boarding",
      },
      {
        buque: "Costa del Sur",
        naviera: "Río Shipping",
        hora: "13:30",
        estadia: "20 h",
        sitio: "Sitio 1",
        origen: "Puerto La Plata",
        carga: "Carga general",
        destino: "Rio Grande",
        estado: "En tiempo",
      },
      {
        buque: "Isla Marina",
        naviera: "Naviera Austral",
        hora: "16:20",
        estadia: "24 h",
        sitio: "Sitio 5",
        origen: "Puerto La Plata",
        carga: "Pesca congelada",
        destino: "Punta Arenas",
        estado: "Pendiente de confirmación",
      },
    ],
  },
  manana: {
    arribos: [
      {
        buque: "Andes Carrier",
        naviera: "Continental Lines",
        hora: "07:50",
        estadia: "20 h",
        sitio: "Sitio 2",
        origen: "Asunción",
        carga: "Contenedores",
        destino: "Terminal TecPlata",
        estado: "Confirmado",
      },
      {
        buque: "Pampa Trader",
        naviera: "Litoral Cargo",
        hora: "12:05",
        estadia: "12 h",
        sitio: "Sitio 6",
        origen: "Rosario",
        carga: "Granel",
        destino: "Depósito Este",
        estado: "En tiempo",
      },
    ],
    salidas: [
      {
        buque: "Mar Azul",
        naviera: "Buenos Aires Shipping",
        hora: "09:10",
        estadia: "18 h",
        sitio: "Sitio 4",
        origen: "Puerto La Plata",
        carga: "Vehículos",
        destino: "Santos",
        estado: "Confirmado",
      },
      {
        buque: "Río de la Plata I",
        naviera: "Oceanic SA",
        hora: "14:45",
        estadia: "15 h",
        sitio: "Sitio 3",
        origen: "Puerto La Plata",
        carga: "Contenedores",
        destino: "Montevideo",
        estado: "En tiempo",
      },
    ],
  },
  semana: {
    arribos: [
      {
        buque: "Atlántico Sur",
        naviera: "Global Maritime",
        hora: "10/02/2026",
        estadia: "30 h",
        sitio: "Sitio 7",
        origen: "Hamburgo",
        carga: "Carga general",
        destino: "Zona Logística",
        estado: "Programado",
      },
      {
        buque: "Río Grande V",
        naviera: "MarSur",
        hora: "13/02/2026",
        estadia: "26 h",
        sitio: "Sitio 2",
        origen: "Rio Grande",
        carga: "Contenedores",
        destino: "Terminal TecPlata",
        estado: "Programado",
      },
      {
        buque: "Bahía Venture",
        naviera: "Atlantic Cargo",
        hora: "17/02/2026",
        estadia: "22 h",
        sitio: "Sitio 1",
        origen: "Bahía Blanca",
        carga: "Granel",
        destino: "Depósito Norte",
        estado: "Programado",
      },
    ],
    salidas: [
      {
        buque: "Costa Norte",
        naviera: "Litoral Cargo",
        hora: "11/02/2026",
        estadia: "28 h",
        sitio: "Sitio 5",
        origen: "Puerto La Plata",
        carga: "Pesca congelada",
        destino: "Valparaíso",
        estado: "Programado",
      },
      {
        buque: "Delta Mar II",
        naviera: "Naviera Austral",
        hora: "15/02/2026",
        estadia: "17 h",
        sitio: "Sitio 3",
        origen: "Puerto La Plata",
        carga: "Contenedores",
        destino: "Rotterdam",
        estado: "Programado",
      },
      {
        buque: "Patria Trader",
        naviera: "Global Maritime",
        hora: "19/02/2026",
        estadia: "19 h",
        sitio: "Sitio 6",
        origen: "Puerto La Plata",
        carga: "Carga general",
        destino: "Cartagena",
        estado: "Programado",
      },
    ],
  },
}
